M48
; DRILL file {KiCad (6.0.11)} date Fri Jan  5 14:55:06 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-05T14:55:06+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X193.37Y-78.8
X198.45Y-130.87
X226.39Y-130.87
X241.63Y-80.07
T0
M30
