M48
; DRILL file {KiCad (6.0.11)} date Fri Jan  5 14:59:16 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-05T14:59:16+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X120.075Y-79.75
X125.155Y-131.82
X153.095Y-131.82
X168.335Y-81.02
T0
M30
